# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 344ad1cffbab3dc6bd315ac810f45148b13ad639d8b339846c6d0957b7b968898826ae672518efb4d830e9dbd7d09377c5abff04268242294906d6f74d9775a7

test:
  secret_key_base: b9bc9921f46aee1ae4a0348c06223f93e3f4cdd17411fc03630f001c96326c840ce30bc978931ef1fd596be55219da1fcaf006f618625889a22d2760140f1da7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
